<?php
/**
 * Created by PhpStorm.
 * User: mkkn
 * Date: 2015/01/11
 * Time: 21:34
 */

namespace Chatbox\Chatbox\Eloquent;

use Illuminate\Database\Eloquent\Model;
use Chatbox\Chatbox\Schema\Base as SchemaBase;
use Chatbox\Chatbox\Schema\SchemaContainer;

abstract class Base extends Model{

    /**
     * @var SchemaBase
     */
    protected $schema;

    public function __construct(array $attributes = array())
    {
        if($this->schema){
            $this->schema = SchemaContainer::getInstance()->getSchema($this->schema);
        }else{
            throw new \Exception("schema name not set");
        }
        $this->table = $this->schema->getName();
        parent::__construct($attributes); // TODO: Change the autogenerated stub
    }

}